#!/usr/bin/perl
use strict;
use warnings;
use App::Egaz;

App::Egaz->run;

=head1 OVERVIEW

For help with App::Egaz, run "egaz help"

=cut

__END__

perl -I lib/ script/egaz help

lastz t/pseudocat.fa t/pseudopig.fa > t/default.lav
lavToPsl t/default.lav t/default.psl

perl -I lib/ script/egaz lav2axt t/default.lav
perl -I lib/ t/04-lav2axt.t

perl -I lib/ script/egaz lav2psl t/default.lav
perl -I lib/ t/05-lav2psl.t

perl -I lib/ script/egaz formats
perl -I lib/ t/06-formats.t

perl -I lib/ t/07-maskfasta.t

perl -I lib/ script/egaz masked <(echo -e ">1\nNNNN\n")
perl -I lib/ t/08-masked.t

perl -I lib/ script/egaz partition
perl -I lib/ t/09-partition.t

